name: Automatyczny Wykrywacz Live

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-live:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie repozytorium
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalacja yt-dlp
        run: |
          pip install yt-dlp

      - name: Wykrywanie transmisji
        run: |
          python get_stream.py

      - name: Zapis wyników do repozytorium
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stream.json
          git diff --staged --quiet || (git commit -m "Auto-update live m3u8" && git push)
