name: Sync Kanon DiscoAdamusa Playlist

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generowanie nowego index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python build_site.py

      - name: Automatyczny commit i push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-sync playlist: update index.html"
          file_pattern: "index.html"
